config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  
  resources :comments
  resources :users
  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :content, presence: true
    validates :content, lenght: {maximum: 140}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    validates :name, presence:true
    validates :name, format: /[A-Z][a-z]*/

    scope :created_today, -> {where("created_at > ?", Date.today.beginning_of_day)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def created
  end

  def new
  end

  def show 
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def created
  end

  def new
  end

  def show 
  end

  def update
  end

  def destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
  
    def create
    end
  
    def new
        @post = Post.new 
    end
  
    def show 
        @post = Post.find(params[:title, :body])
    end
  
    def update
    end
  
    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
  
    def new
        @user = User.new
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    def create
      @user = User.new(user_params)
        if @user.save
          redirect_to users_path
        else
          render :new
        end
    end
    
    def update
      @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to users_path
        else
          render :edit
        end
    end
    
    def show
        #@user = User.find(params[:id])
      @user = User.find(params[:id])
        if @user.destroy
          flash[:notice] = 'User has been destroyed'
          redirect_to users_path
        else
          flash[:alert] = 'Something went wrong'
          redirect_to users_path
        end
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<a href="users/">Users</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lekcja3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= link_to 'Add New Post', new_post_path %>

<h1>Posts</h1>
<table>
  <tr>
    <th>Post ID</th>
    <th>User ID</th>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.user_id %></td>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= link_to post.body, post_path(post)%></td>
      
      
    </tr>
  <% end %>
</table>

app/views/users/_user.html.erb
<%= form_with model: @user do |form| %>
    <%= form.text_field :name %>
    <%= form.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'user' %>

app/views/users/index.html.erb
 <%= link_to 'Add New User', new_user_path %>

 <h1>Users</h1>
 <table>
   <tr>
     <th>User ID</th>
     <th>User Name</th>
     <th>Edit</th>
     <th>Delete</th>
   </tr>
   <% @users.each do |user| %>
     <tr>
       <td><%= user.id %></td>
       <td><%= link_to user.name, user_path(user) %></td>
       <td><%= link_to 'Edit', edit_user_path(user) %></td>
       <td><%= link_to 'Delete User', user_path(user), method: :delete %></td>
     </tr>
   <% end %>
 </table>

app/views/users/new.html.erb
<%= render 'user' %>

app/views/users/show.html.erb
<%= @user.name %>